=== yashmaheshwari11/xmlRepo/XmlXsdProject/src/movies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zensar.com/movies" xmlns:zen="http://www.zensar.com/movies" elementFormDefault="qualified">
<element name="movies">
	<complexType>
		<sequence>
		<element name="movie" maxOccurs="unbounded">
			<complexType>
				<sequence>
					<element name="code">
						<simpleType>
							<restriction base="int">
								<totalDigits value="4"></totalDigits>
								<minInclusive value="5001"></minInclusive>
								<maxExclusive value="6000"></maxExclusive>
							</restriction>
						</simpleType>
					</element>
					
					<element name="title" type="string"></element>
		<element name="release-date" type="date" minOccurs="0"></element>
		<element name="theatre-name">
		<simpleType>
			<restriction base="string">
			<minLength value="4"></minLength>
			<maxLength value="30"></maxLength>
			</restriction>
		</simpleType>
		</element>
					
				</sequence>
			</complexType>
		</element>
		
		
		</sequence>
	</complexType>
</element>
</schema>

=== yashmaheshwari11/xmlRepo/XmlXsdProject/bin/movieDetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<zen:movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:zen="http://www.zensar.com/movies" xsi:schemaLocation="http://www.zensar.com/movies movies.xsd ">
  <zen:movie>
    <zen:code>5001</zen:code>
    <zen:title>Drishyam</zen:title>
    <zen:theatre-name>Inox</zen:theatre-name>
  </zen:movie>
  
    <zen:movie>
    <zen:code>5002</zen:code>
    <zen:title>Raaz</zen:title>
    <zen:theatre-name>PVR Cinepolis</zen:theatre-name>
  </zen:movie>
  
</zen:movies>
